### ISSUE TITLE
java.awt.geom.Rectangle2D$Double cannot be cast to java.awt.Rectangle

### ISSUE THREAD

**Issue by wez** [Engidea/FreeRoutingNew#5]
I hit this as soon as I open up my design :-(

```
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: java.awt.geom.Rectangle2D$Double cannot be cast to java.awt.Rectangle
	at freert.graphics.GdiContext.fill_circle(GdiContext.java:284)
	at freert.graphics.GdiContext.fill_area(GdiContext.java:420)
	at board.items.BrdArea.draw(BrdArea.java:313)
	at board.items.BrdItem.draw(BrdItem.java:945)
	at board.RoutingBoard.draw(RoutingBoard.java:1151)
	at interactive.IteraBoard.draw(IteraBoard.java:780)
	at gui.BoardPanel.paintComponent(BoardPanel.java:280)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JViewport.paint(JViewport.java:728)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5217)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent.paint(JComponent.java:1042)
	at java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:79)
	at sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:116)
	at java.awt.Container.paint(Container.java:1975)
	at java.awt.Window.paint(Window.java:3904)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:842)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by wez** [comment]
This seems to help:

```
diff --git a/src/freert/graphics/GdiContext.java b/src/freert/graphics/GdiContext.java
index 3fbcade..eef9e9e 100644
--- a/src/freert/graphics/GdiContext.java
+++ b/src/freert/graphics/GdiContext.java
@@ -150,7 +150,7 @@ public final class GdiContext implements java.io.Serializable
       if (p_color == null) return;

       Graphics2D g2 = (Graphics2D) p_g;
-      Rectangle clip_shape = (Rectangle) p_g.getClip();
+      Rectangle clip_shape = p_g.getClip().getBounds();
       // the class member update_box cannot be used here, because the dirty rectangle is internally enlarged by the system.
       // Therefore we can not improve the performance by using an update octagon instead of a box.
       ShapeTileBox clip_box = coordinate_transform.screen_to_board(clip_shape);
@@ -281,7 +281,7 @@ public final class GdiContext implements java.io.Serializable
       Point2D center = coordinate_transform.board_to_screen(p_circle.center.to_float());
       double radius = coordinate_transform.board_to_screen(p_circle.radius);

-      if (!point_near_rectangle(center.getX(), center.getY(), (Rectangle) p_g.getClip(), radius))  return;
+      if (!point_near_rectangle(center.getX(), center.getY(), p_g.getClip().getBounds(), radius))  return;

       double diameter = 2 * radius;
       Ellipse2D circle = new Ellipse2D.Double(center.getX() - radius, center.getY() - radius, diameter, diameter);
@@ -317,7 +317,7 @@ public final class GdiContext implements java.io.Serializable
          Point2D center = coordinate_transform.board_to_screen(curr_ellipse.center);
          double bigger_radius = coordinate_transform.board_to_screen(curr_ellipse.bigger_radius);

-         if (!point_near_rectangle(center.getX(), center.getY(), (Rectangle) p_g.getClip(), bigger_radius))
+         if (!point_near_rectangle(center.getX(), center.getY(), p_g.getClip().getBounds(), bigger_radius))
             {
             continue;
             }
@@ -427,7 +427,7 @@ public final class GdiContext implements java.io.Serializable
             System.out.println("GraphicsContext.fill_area: shape not bounded");
             return;
             }
-         Rectangle clip_shape = (Rectangle) p_g.getClip();
+         Rectangle clip_shape = p_g.getClip().getBounds();
          ShapeTileBox clip_box = coordinate_transform.screen_to_board(clip_shape);
          if (!border.bounding_box().intersects(clip_box))
             {
```

**Comment by Engidea** [comment]
Can you send me the file that throw the exception ?

**Comment by wez** [comment]
Since applying the patch above I haven't hit this, and I've been iterating (the kicad schematics are machine generated), but this file probably will also manifest the same problem:

[kicad_schematic.dsn.txt](https://github.com/Engidea/FreeRoutingNew/files/909136/kicad_schematic.dsn.txt)

**Comment by Engidea** [comment]
Should be fixed in current commit, you should be able to use the current build, as it is
I am also looking into the build.xml so you may build the code if you wish to
Let me know is you can use the build committed

**Comment by wez** [comment]
Thanks!  Aside from #3 still being an issue, this is working, thanks!

**Comment by tempo63** [comment]
I'm having the same problem. what did you do to solve this?

**Comment by tempo63** [comment]
I'm having the same exact problem and I can't find anything about it anywhere. what did you do to solve this. You mentioned that bit of code that solved it? where did you paste it? I used the binary that I downloaded, and I compiled it with netbeans too, but same result. (I'm on OSX 10.9)

**Comment by Engidea** [comment]
The startup panel has three tabs User,Output,Error where you can see and copy the backtrace
Paste it here and I will fix it for you
